### ISSUE TITLE
[Server] Error with NoCredentialsError(botocore) 

### ISSUE THREAD

**Issue by elijah0430** [wafflestudio18-5/team8-server#60]
in 
POST, /user/
PUT /user/me/
GET /user/(pk)/
api testing, NoCredentials Error occurs. 

example traceback: PUT /user/me
```
Traceback (most recent call last):
  File "/home/jongwon/Documents/Zoom/team8-server/podo_server/user/tests_user.py", line 456, in test_put_user
    response=self.client.put(
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/test/client.py", line 767, in put
    response = super().put(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/test/client.py", line 429, in put
    return self.generic('PUT', path, data, content_type,
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/test/client.py", line 470, in generic
    return self.request(**r)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/test/client.py", line 709, in request
    self.check_exception(response)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/test/client.py", line 571, in check_exception
    raise exc_value
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/home/jongwon/anaconda3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/jongwon/anaconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/jongwon/anaconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 66, in default
    return tuple(item for item in obj)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 66, in <genexpr>
    return tuple(item for item in obj)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/files/base.py", line 78, in __iter__
    for chunk in self.chunks():
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/files/base.py", line 55, in chunks
    self.seek(0)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/files/utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 43, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 427, in _open
    f = S3Boto3StorageFile(name, mode, self)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 107, in __init__
    self.obj.load()
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/signers.py", line 162, in sign
    auth.add_auth(request)
  File "/home/jongwon/Documents/Zoom/team8-server/venv/lib/python3.8/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by callmejustdodo** [comment]
언제 어떤 상황에서 생기는거죠? 저는 main 기준 안생기는걸 확인했는데 ㅠㅠ
